name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for required files
        run: |
          if [ -f "index.html" ]; then
            echo "El archivo index.html existe. Todo correcto."
          else
            echo "Error: No se encontró index.html"
            exit 1
          fi

      - name: Echo success message
        run: echo "Validación completada con éxito"